// Parity test: the TS aggregator must match the Python reference (niw_stats.stats.aggregate)
// on a fixture whose expected outputs were generated BY the Python functions.
import { describe, expect, it } from "vitest";

import type { SlimRecord } from "../types";
import * as agg from "./aggregate";
import fixture from "./__fixtures__/parity.json";

const records = fixture.records as unknown as SlimRecord[];

interface Case {
  name: string;
  fn: string;
  args: unknown[];
  expected: unknown;
}

function run(c: Case): unknown {
  switch (c.fn) {
    case "distribution":
      return agg.distribution(records, c.args[0] as string, c.args[1] as boolean);
    case "approval_rate":
      return agg.approvalRate(records);
    case "approval_rate_by_group":
      return agg.approvalRateByGroup(records, c.args[0] as string, c.args[1] as boolean);
    case "filter_count":
      return agg.filterByRange(records, c.args[0] as number, c.args[1] as number).length;
    default:
      throw new Error(`unknown fn ${c.fn}`);
  }
}

describe("TS/Python aggregation parity", () => {
  for (const c of fixture.cases as Case[]) {
    it(`matches Python for ${c.name}`, () => {
      expect(run(c)).toEqual(c.expected);
    });
  }

  it("windowFromRange matches Python", () => {
    const w = fixture.window_from_range as { key: string; now: number; expected: number[] };
    expect(agg.windowFromRange(w.key, w.now)).toEqual(w.expected);
  });
});

describe("re-file detection parity", () => {
  const mr = fixture.mark_refiled as {
    records: SlimRecord[];
    expected: { id: string; refiled: boolean | null; refiled_url: string | null; refile_approval: boolean | null }[];
  };
  it("matches Python mark_refiled", () => {
    const recs = mr.records.map((r) => ({ ...r })) as unknown as SlimRecord[];
    agg.markRefiled(recs);
    const got = recs.map((r) => ({
      id: r.id,
      refiled: r.refiled ?? null,
      refiled_url: r.refiled_url ?? null,
      refile_approval: r.refile_approval ?? null,
    }));
    expect(got).toEqual(mr.expected);
  });
});

describe("run selection / composite voting parity", () => {
  const sv = fixture.select_view as {
    records: SlimRecord[];
    cases: { run: string; expected: { id: string; outcome: string; run: string }[] }[];
  };
  for (const c of sv.cases) {
    it(`matches Python select_view for run=${c.run}`, () => {
      const got = agg.selectView(sv.records, c.run).map((r) => ({ id: r.id, outcome: r.outcome, run: r.run }));
      expect(got).toEqual(c.expected);
    });
  }
});

describe("drill-down filters", () => {
  it("filters by outcome", () => {
    const out = agg.applyFilters(records, { outcome: ["approved"] });
    expect(out.every((r) => r.outcome === "approved")).toBe(true);
    expect(out.length).toBe(records.filter((r) => r.outcome === "approved").length);
  });

  it("filters by a citation bucket (finer bins)", () => {
    const out = agg.applyFilters(records, { citations: ["31–50"] }); // the record with 50 citations
    expect(out).toHaveLength(1);
    expect(out[0].citations[0]).toBe(50);
  });

  it("combines filters across fields with AND", () => {
    const out = agg.applyFilters(records, { outcome: ["approved"], degree: ["PhD"] });
    expect(out.every((r) => r.outcome === "approved" && r.degree === "PhD")).toBe(true);
    expect(out.length).toBeGreaterThan(0);
  });

  it("ORs multiple values within one field (multi-select)", () => {
    const out = agg.applyFilters(records, { degree: ["PhD", "Masters"] });
    expect(out.every((r) => r.degree === "PhD" || r.degree === "Masters")).toBe(true);
    expect(out.length).toBe(
      records.filter((r) => r.degree === "PhD" || r.degree === "Masters").length,
    );
    // The union is at least as large as either single-value filter.
    expect(out.length).toBeGreaterThanOrEqual(
      agg.applyFilters(records, { degree: ["PhD"] }).length,
    );
  });

  it("empty filters return everything", () => {
    expect(agg.applyFilters(records, {})).toBe(records);
  });

  it("an empty value list is treated as no constraint", () => {
    expect(agg.applyFilters(records, { degree: [] })).toBe(records);
  });

  it("filters by Unknown for a categorical field (not-mentioned)", () => {
    const out = agg.applyFilters(records, { degree: ["Unknown"] });
    expect(out.every((r) => r.degree == null)).toBe(true);
    expect(out.length).toBe(records.filter((r) => r.degree == null).length);
  });

  it("filters by Unknown for a numeric field (not known)", () => {
    const out = agg.applyFilters(records, { citations: ["Unknown"] });
    expect(out.every((r) => !r.citations[1])).toBe(true);
  });
});

describe("effective date (stated I-140 decision date, else post date)", () => {
  // 2026-05-15 post reporting an I-140 decided 2025-03-01 (the I-485-posted-later case).
  const stale = {
    created_utc: Date.UTC(2026, 4, 15) / 1000,
    decision_utc: Date.UTC(2025, 2, 1) / 1000,
    outcome: "approved",
  } as unknown as SlimRecord;
  const fresh = { created_utc: Date.UTC(2026, 4, 20) / 1000, outcome: "denied" } as unknown as SlimRecord;

  it("effectiveUtc prefers decision_utc and falls back to created_utc", () => {
    expect(agg.effectiveUtc(stale)).toBe(stale.decision_utc);
    expect(agg.effectiveUtc(fresh)).toBe(fresh.created_utc);
  });

  it("filterByRange windows on the effective date", () => {
    const start = Date.UTC(2026, 0, 1) / 1000;
    expect(agg.filterByRange([stale, fresh], start, null)).toEqual([fresh]);
    expect(agg.filterByRange([stale, fresh], null, start)).toEqual([stale]);
  });

  it("quarter functions bucket by the effective date", () => {
    expect(agg.availableQuarters([stale, fresh])).toEqual(["2026-Q2", "2025-Q1"]);
    expect(agg.filterByQuarters([stale, fresh], new Set(["2025-Q1"]))).toEqual([stale]);
    const series = agg.quarterSeries([stale, fresh]);
    expect(series.map((p) => p.quarter)).toEqual(["2025-Q1", "2026-Q2"]);
    expect(series[0].approved).toBe(1);
    expect(series[1].denied).toBe(1);
  });
});
